/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py:43: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  result = getattr(asarray(obj), method)(*args, **kwds)
Traceback (most recent call last):
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 113, in run
    self.train()
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 65, in train
    action = self.actor.get_action(state)
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/actor.py", line 30, in get_action
    state = np.reshape(state, [1, self.state_dim])
  File "<__array_function__ internals>", line 180, in reshape
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 298, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 54, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 43, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: cannot reshape array of size 2 into shape (1,3)
Exception in thread Thread-19:
Traceback (most recent call last):
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 113, in run
    self.train()
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 65, in train
    action = self.actor.get_action(state)
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/actor.py", line 30, in get_action
    state = np.reshape(state, [1, self.state_dim])
  File "<__array_function__ internals>", line 180, in reshape
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 298, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 54, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 43, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: cannot reshape array of size 2 into shape (1,3)
Traceback (most recent call last):
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 113, in run
    self.train()
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 65, in train
    action = self.actor.get_action(state)
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/actor.py", line 30, in get_action
    state = np.reshape(state, [1, self.state_dim])
  File "<__array_function__ internals>", line 180, in reshape
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 298, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 54, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 43, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: cannot reshape array of size 2 into shape (1,3)
Exception in thread Thread-13:
Traceback (most recent call last):
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 113, in run
    self.train()
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 65, in train
    action = self.actor.get_action(state)
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/actor.py", line 30, in get_action
    state = np.reshape(state, [1, self.state_dim])
  File "<__array_function__ internals>", line 180, in reshape
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 298, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 54, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 43, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: cannot reshape array of size 2 into shape (1,3)
Traceback (most recent call last):
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 113, in run
    self.train()
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 65, in train
    action = self.actor.get_action(state)
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/actor.py", line 30, in get_action
    state = np.reshape(state, [1, self.state_dim])
  File "<__array_function__ internals>", line 180, in reshape
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 298, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 54, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 43, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: cannot reshape array of size 2 into shape (1,3)
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 113, in run
    self.train()
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 65, in train
    action = self.actor.get_action(state)
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/actor.py", line 30, in get_action
    state = np.reshape(state, [1, self.state_dim])
  File "<__array_function__ internals>", line 180, in reshape
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 298, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 54, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 43, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: cannot reshape array of size 2 into shape (1,3)
Traceback (most recent call last):
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 113, in run
    self.train()
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 65, in train
    action = self.actor.get_action(state)
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/actor.py", line 30, in get_action
    state = np.reshape(state, [1, self.state_dim])
  File "<__array_function__ internals>", line 180, in reshape
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 298, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 54, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 43, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: cannot reshape array of size 2 into shape (1,3)
Exception in thread Thread-12:
Traceback (most recent call last):
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 113, in run
    self.train()
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 65, in train
    action = self.actor.get_action(state)
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/actor.py", line 30, in get_action
    state = np.reshape(state, [1, self.state_dim])
  File "<__array_function__ internals>", line 180, in reshape
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 298, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 54, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 43, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: cannot reshape array of size 2 into shape (1,3)
Traceback (most recent call last):
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 113, in run
    self.train()
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 65, in train
    action = self.actor.get_action(state)
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/actor.py", line 30, in get_action
    state = np.reshape(state, [1, self.state_dim])
  File "<__array_function__ internals>", line 180, in reshape
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 298, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 54, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 43, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: cannot reshape array of size 2 into shape (1,3)
Exception in thread Thread-15:
Traceback (most recent call last):
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 113, in run
    self.train()
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 65, in train
    action = self.actor.get_action(state)
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/actor.py", line 30, in get_action
    state = np.reshape(state, [1, self.state_dim])
  File "<__array_function__ internals>", line 180, in reshape
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 298, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 54, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 43, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: cannot reshape array of size 2 into shape (1,3)
Traceback (most recent call last):
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 113, in run
    self.train()
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 65, in train
    action = self.actor.get_action(state)
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/actor.py", line 30, in get_action
    state = np.reshape(state, [1, self.state_dim])
  File "<__array_function__ internals>", line 180, in reshape
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 298, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 54, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 43, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: cannot reshape array of size 2 into shape (1,3)
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 113, in run
    self.train()
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 65, in train
    action = self.actor.get_action(state)
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/actor.py", line 30, in get_action
    state = np.reshape(state, [1, self.state_dim])
  File "<__array_function__ internals>", line 180, in reshape
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 298, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 54, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 43, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: cannot reshape array of size 2 into shape (1,3)
Traceback (most recent call last):
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 113, in run
    self.train()
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 65, in train
    action = self.actor.get_action(state)
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/actor.py", line 30, in get_action
    state = np.reshape(state, [1, self.state_dim])
  File "<__array_function__ internals>", line 180, in reshape
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 298, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 54, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 43, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: cannot reshape array of size 2 into shape (1,3)
Exception in thread Thread-14:
Traceback (most recent call last):
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 113, in run
    self.train()
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 65, in train
    action = self.actor.get_action(state)
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/actor.py", line 30, in get_action
    state = np.reshape(state, [1, self.state_dim])
  File "<__array_function__ internals>", line 180, in reshape
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 298, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 54, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 43, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: cannot reshape array of size 2 into shape (1,3)
Traceback (most recent call last):
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 113, in run
    self.train()
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 65, in train
    action = self.actor.get_action(state)
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/actor.py", line 30, in get_action
    state = np.reshape(state, [1, self.state_dim])
  File "<__array_function__ internals>", line 180, in reshape
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 298, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 54, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 43, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: cannot reshape array of size 2 into shape (1,3)
Exception in thread Thread-17:
Traceback (most recent call last):
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 113, in run
    self.train()
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 65, in train
    action = self.actor.get_action(state)
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/actor.py", line 30, in get_action
    state = np.reshape(state, [1, self.state_dim])
  File "<__array_function__ internals>", line 180, in reshape
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 298, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 54, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 43, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: cannot reshape array of size 2 into shape (1,3)
Traceback (most recent call last):
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 113, in run
    self.train()
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 65, in train
    action = self.actor.get_action(state)
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/actor.py", line 30, in get_action
    state = np.reshape(state, [1, self.state_dim])
  File "<__array_function__ internals>", line 180, in reshape
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 298, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 54, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 43, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: cannot reshape array of size 2 into shape (1,3)
Exception in thread Thread-18:
Traceback (most recent call last):
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 113, in run
    self.train()
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 65, in train
    action = self.actor.get_action(state)
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/actor.py", line 30, in get_action
    state = np.reshape(state, [1, self.state_dim])
  File "<__array_function__ internals>", line 180, in reshape
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 298, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 54, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 43, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: cannot reshape array of size 2 into shape (1,3)
Traceback (most recent call last):
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 113, in run
    self.train()
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 65, in train
    action = self.actor.get_action(state)
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/actor.py", line 30, in get_action
    state = np.reshape(state, [1, self.state_dim])
  File "<__array_function__ internals>", line 180, in reshape
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 298, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 54, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 43, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: cannot reshape array of size 2 into shape (1,3)
Exception in thread Thread-16:
Traceback (most recent call last):
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 113, in run
    self.train()
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/worker.py", line 65, in train
    action = self.actor.get_action(state)
  File "/Users/daehungo/Desktop/DataCapstone/github/DeepHedging/A3C/actor.py", line 30, in get_action
    state = np.reshape(state, [1, self.state_dim])
  File "<__array_function__ internals>", line 180, in reshape
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 298, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 54, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/Users/daehungo/yes/envs/colab/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 43, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: cannot reshape array of size 2 into shape (1,3)